# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e0d52498e936e931b552c34584c8ee4e033faff1fb4c945d398cda7ed338954f2c40c7936cb2fd5e51b928d15014dc9b670759f865a222e9e058b8255b3c2ae

test:
  secret_key_base: fad7367a06d0a1021d3df74b8e33ee8d5e74223e0457ffe71940a2c706826549e550eca1e41c730b0685ada791bbd7487e543169ee0edf2b29e2c1087791f619

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
